include(":commonutil")
include(":readview")
include(":zeroconfigutil")
include(":libzeroconfig")
include(":analytics_lib")
include(":app")
rootProject.name = "novelrecommend"
include(":analytics_lib_api")
include(":login")
include(":login_api")
include(":commonui")
include(":setting")
include(":setting_api")
